apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: k3-cluster 
servers: 1
agents: 0
image: rancher/k3s:v1.24.10-k3s1
ports:
- port: 4222:4222
  nodeFilters:
  - loadbalancer
registries:
  create:
    name: nats.working.registry
    host: "0.0.0.0"
    hostPort: "5001"
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable=metrics-server
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
